version: '3'

services:
  frontend:
    build: ./frontend-react
    ports:
      - "3000:3000"

  apigateway:
    build: ./api-gateway-nodejs
    ports:
      - "3001:3001"

  orderprocessor:
    build: ./order-processor-python
    ports:
      - "5000:5000"

  compliance:
    build: ./compliance-service-dotnet
    ports:
      - "5001:5001"

  ledger:
    build: ./ledger-service-java
    ports:
      - "6000:6000"