version: '3'

services:
  frontend:
    image: albint565/emart_frontend
    ports:
      - "3000:3000"

  apigateway:
    image: albint565/emart_api
    ports:
      - "3001:3001"

  orderprocessor:
    image: albint565/emart_order_processor
    ports:
      - "5000:5000"

  compliance:
    image: albint565/emart_compliance
    ports:
      - "5001:5001"

  ledger:
    image: albint565/emart_ledger
    ports:
      - "6000:6000"